### ISSUE TITLE
We should manage the repo topics via dev-kit

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#233] opened 2017-02-06 13:56 UTC
https://github.com/blog/2309-introducing-topics

And here are the best practices for Symfony bundles: 
http://symfony.com/blog/standardizing-the-github-topics-for-symfony-repositories

**Comment by OskarStark** [comment] 2017-02-07 12:27
> From the symfony blog post:
> If your repository is a Symfony Bundle, consider using the following four topics (in addition to your own topics):
>
> `php`, it may seem redundant but it contributes to make the PHP ecosystem look as big as it really is;
> `symfony`, recommended for any repository related to the Symfony project (don't add the Symfony version (symfony2, symfony3) to avoid fragmentation);
> `bundle`, short, memorable and ideal for Symfony bundles;
>`symfony-bundle`, it may seem redundant too, but it's useful to exclude projects that use our bundle topic and are not related to Symfony.

**Comment by OskarStark** [comment] 2017-02-07 12:28
IMO we should add something sonata specific: `sonata` and `sonata-admin`

**Comment by core23** [comment] 2017-05-12 10:11
We still don't have any topics for our projects... Anyone (except @rande) have permissions to do this?

**Comment by rande** [comment] 2017-05-16 11:44
you need to be an admin to add topic (https://help.github.com/articles/repository-permission-levels-for-an-organization/) however, I cannot give this level to contributor as the admin role has to much privilege.

Can you send me the list for each bundle, I will add them shorly ?

Thanks

**Comment by OskarStark** [comment] 2017-05-16 11:46
> Can you send me the list for each bundle, I will add them shorly ?

I think this could be done via the github api with dev-kit, so we could add a PR here and @Soullivaneuh can execute it

**Comment by jordisala1991** [comment] 2018-04-01 21:15
Closing as duplicate of #392 , the other one has more info.

**Closed by jordisala1991** 2018-04-01 21:15 UTC
Labels: enhancement
