### ISSUE TITLE
Problem with UPGRADE and CHANGELOG files

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#70] opened 2016-05-16 10:37 UTC
We have a little problem with the new UPGRADE and CHANGELOG files. Everything should be mentioned in these files, that's okay 👍 But every time someone add a new line and we merge this, everybody who added a line to the same part of te file needs to rebase his PR. That's very annoying.

**Comment by greg0ire** [comment] 2016-05-16 17:53
Maybe we should be responsible for it, and not the contributors ? It seems symfony is doing that : https://github.com/symfony/symfony/commits/master/CHANGELOG-3.0.md

**Comment by Soullivaneuh** [comment] 2016-05-16 22:51
> But every time someone add a new line and we merge this, everybody who added a line to the same part of te file needs to rebase his PR. That's very annoying.

Do you have a concrete case? I merged several PR on a time without having to rebase it for that.

> Maybe we should be responsible for it, and not the contributors ?

Maybe. But this was not done before. This is what I do for my projects. But my projects have 3 PR every 6 months.

This will be harder to write the changelog manually on each release. We have the risk to forget it. Plus, maybe we can do mistake while writing the changelog because we didn't understand a PR we didn't manage.

Forcing people to update the change-log will ensure not forget and open discussion for a better description on the dedicated PR.

> It seems symfony is doing that :

AFAIK, Symfony has a internal tool to generate special commit message and then the Changelog.

This could be great to have that but this cannot be done easily and this means that **every** contributor should strictly follow the same merging rules, even harder.



I'm open for a easy technical solution, but I would like to not remove Changelog/Upgrade note on PR for now.

**Comment by Soullivaneuh** [comment] 2016-05-16 23:36
I saw @greg0ire put a changelog line of top of the list: https://github.com/sonata-project/SonataAdminBundle/pull/3791/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR7

Does this could have an influence?

**Comment by greg0ire** [comment] 2016-05-17 08:39
> I saw @greg0ire put a changelog line of top of the list

We are putting releases in reverse-chronological order, putting the content also in reverse-chronological order makes sense too, doesn't it ?

**Closed** 2016-05-17 11:49 UTC
Labels: help wanted

**Comment by core23** [comment] 2016-05-17 14:34
> We are putting releases in reverse-chronological order...

Haved I missed something? Where do you get this information @greg0ire

**Comment by greg0ire** [comment] 2016-05-17 14:34
> Haved I missed something? Where do you get this information @greg0ire 

On http://keepachangelog.com

**Comment by core23** [comment] 2016-05-17 14:40
>> Haved I missed something? Where do you get this information @greg0ire 
>
>On http://keepachangelog.com
>
>> List releases in reverse-chronological order (newest on top).

Didn't have that in mind when creating the new entries. Maybe leave a hint in the `Contributing` docs?

**Comment by greg0ire** [comment] 2016-05-17 14:44
Well the website talks only about the **releases**, not their content. Maybe we should agree on that first.

Please vote :+1: for reverse chronological order in content, :-1: for chronological answer, and :confused: for no order.

**Comment by core23** [comment] 2016-05-17 15:38
After thinking a few minutes. We should group changes like the following.

```
### Added
- Foo
- Added something
- Added AbstractAdmin, replacing Admin
- Added the `getFooButton` method to the `AbstractAdmin`
- Added the `getSearchResultLink` method to the `AbstractAdmin`
- Added the `getSearchResultButton` method to the `AbstractAdmin`
- Bar
```

**Comment by Soullivaneuh** [comment] 2016-05-17 15:42
@core23 I saw your example but I don't understand what you're trying to explain...

**Comment by greg0ire** [comment] 2016-05-17 15:42
He means changes to the `AbstractAdmin` should be grouped together.

**Comment by Soullivaneuh** [comment] 2016-05-19 08:31
Oh ok. Yes it would be great.

After all, keep in mind this is "just a changelog". We have to be clear but not to heavy on it. :wink:

**Comment by greg0ire** [comment] 2016-05-22 15:38
Idea: how about storing changelogs (anf upgrade notes?) in *merge* commits? It would make it easy to generate the log !

**Comment by greg0ire** [comment] 2016-05-23 09:46
ping @sonata-project/contributors

**Comment by Soullivaneuh** [comment] 2016-05-23 09:51
> in merge commits? 

Or squash merge commits.

This is a nice ides but the problem is it's complicated to setup a rule for all sonata contributors without automation.

If one of the contributor forget it, the changelog will be skipped. So it's the same, we have to double check.

I'll work on a tool to generate a changelog from PR body. This have to be checked too but this could simplify the thing.

**Comment by OskarStark** [comment] 2016-05-23 09:53
> AFAIK, Symfony has a internal tool to generate special commit message and then the Changelog.
> 
> This could be great to have that but this cannot be done easily and this means that every contributor should strictly follow the same merging rules, even harder.

I think we should invest some time to create a tool for us which do several tasks, so we can change commit messages easily or makr them as a "fix" "add" oder something like this

With this we could also add the github name to changelog and upgrade files and can create automatic blog posts later on

**Comment by greg0ire** [comment] 2016-05-23 09:54
Squash commits would be fine too indeed!

>  is it's complicated to setup a rule for all sonata contributors

Well the thing is it would be only for contributors that can merge PRs (who named them sonata/contributors ? everyone who proposes a PR that gets merge is a contributors IMO)

**Comment by greg0ire** [comment] 2016-05-23 09:55
> I think we should invest some time to create a tool for us which do several tasks, so we can change commit messages easily or makr them as a "fix" "add" oder something like this

I think commit messages should be left untouched, and but tagging PR changelog notes as FIX or ADD would be a good thing.

**Comment by Soullivaneuh** [comment] 2016-05-23 09:56
Yeah I'm talking about sonata project members. We have the core team but we have also some contributors specific to some projects.

> I think commit messages should be left untouched, and but tagging PR changelog notes as FIX or ADD would be a good thing.

And if a PR changed, added, and fixed some things? :trollface:

**Comment by greg0ire** [comment] 2016-05-23 10:01
> And if a PR changed, added, and fixed some things? :trollface: 

Well you can have several changelog notes in the PR body, where is the problem ? :trollface: . The main point is that the changelog should not be viewed as a subset of the commit message. We should not rework commits because it will make any "verified" tag disappear (I think) and change the commiter of the commit. Plus, the merge commit messages are quite ugly and useless, having them become useful would be good.

**Comment by OskarStark** [comment] 2016-05-23 10:22
here you can see the tool in action: https://youtu.be/VBWVNIUGKW0?t=38m45s

**Comment by Soullivaneuh** [comment] 2016-05-23 10:42
@OskarStark To be analysed but the problem will be the same: How to be sure all sonata team members will follow that without forget it?

We are not a company, it's harder to get sync all together.

And AFAIK, we can't 'block' the merge button.

**Comment by OskarStark** [comment] 2016-05-23 11:23
> And AFAIK, we can't 'block' the merge button.

I think this could be achieved really easy by adding a jenkins job which will ever fail and be required ;-)

**Comment by Soullivaneuh** [comment] 2016-05-23 11:25
> I think this could be achieved really easy by adding a jenkins job which will ever fail and be required ;-)

![image](https://cloud.githubusercontent.com/assets/1698357/15469306/c29e9d0a-20e9-11e6-9747-607e33ca5aed.png)

**Comment by OskarStark** [comment] 2016-05-23 11:26
haha 😄
