### ISSUE TITLE
[DX] Simplify requirements: composer require sonata-project/sonata

### ISSUE THREAD

**Issue by mvhirsch** [sonata-project/dev-kit#242] opened 2017-03-16 12:39 UTC
Hi! 

First: i really love to work with Sonata, thanks for creating! :heart:

But one thing is driving me crazy: installing it. My composer.json is mostly looking like this: 

        "sonata-project/admin-bundle": "^3.0",
        "sonata-project/block-bundle": "^3.0",
        "sonata-project/cache-bundle": "^2.0",
        "sonata-project/classification-bundle": "^3.0",
        "sonata-project/core-bundle": "^3.0",
        "sonata-project/datagrid-bundle": "^2.0",
        "sonata-project/doctrine-orm-admin-bundle": "^3.0",
        "sonata-project/easy-extends-bundle": "^2.0",
        "sonata-project/formatter-bundle": "^3.0",
        "sonata-project/intl-bundle": "^2.0",
        "sonata-project/media-bundle": "^3.0",
        "sonata-project/notification-bundle": "^3.0",
        "sonata-project/page-bundle": "^3.0",
        "sonata-project/seo-bundle": "^2.0",
        "sonata-project/timeline-bundle": "^3.0",
        "sonata-project/user-bundle": "^3.0",

This is actually a setup in one of my projects. Also seeing lots of people doing the same and reporting issues like: https://stackoverflow.com/questions/42626366/sonata-admin-update-bundle-error/42627851
Also many people gets confused on how to upgrade properly, since "bundle A in version X will work with bundle B in version Y" ... this is something composer already takes care about. Why should a developer?

Looking at how I integrated symfony in the (same) composer.json:

        "symfony/symfony": "^2.8",

This package ``symfony/symfony`` utilizes composers feature about package-replacement. So requiring ``symfony/symfony`` in composer will install a full symfony (with all components) instead of requiring each on its one. This helps keeping composer requirements small (in file, not size ;-)).

I know that sonata-project isn't maintaining a mono-repo like symfony does, but is there a way to just (e.g.) ``composer require sonata-project/sonata ^3.0`` and common bundles like admin, media, user, page, ... is ready to work?

By simplifying the requirements, issues like the mentioned above won't happen, since composer take care of updated/patched libraries too.

**Comment by greg0ire** [comment] 2017-03-16 12:44
Yes there is a way! I think we could create [a meta-package](https://getcomposer.org/doc/04-schema.md#type)… the problem is : what bundles should come by default?

**Comment by mvhirsch** [comment] 2017-03-16 12:50
Dunno. I think either all or focus on admin-related packages (admin, core, page, user, ...), such packages typically needed for a CMS-like behaviour.

**Comment by mvhirsch** [comment] 2017-03-16 12:52
Or looking at a working example: 

sonata-project/sandbox: https://github.com/sonata-project/sandbox/blob/2.3/composer.json#L45-L64

**Comment by greg0ire** [comment] 2017-03-16 12:53
Also, you can't really pick a backend storage for the user, can you? IMO, finding a working example is easy to do, in just one command line : `composer require packageA packageB packageC`. Just let Composer figure out the constraints.

**Comment by mvhirsch** [comment] 2017-03-17 08:15
No, I can't pick a backend storage for any user. 
But what about putting all into it and describe how to configure only one?

**Comment by greg0ire** [comment] 2017-03-17 09:18
All packages sounds overkill… but maybe a selection can be done based on download statistics?

> Also, you can't really pick a backend storage for the user, can you?

After more thought, maybe we could pick doctrine orm as the default

**Comment by Soullivaneuh** [comment] 2017-05-11 12:14
As @greg0ire says, all packages are overkill, provinding a common package is not a good solution IMHO.

We have a set of bundles, we do not provide a framework.

BTW, I think Symfony developers are thinking about more splitting of the symfony/symfony package for the future.

**Comment by jordisala1991** [comment] 2018-04-01 21:13
With symfony flex this is simple now. You can just do require sonata-project/admin-bundle and it will setup everything needed.

Closing as this is not necessary, the only use case I could see is to simplify and unify maintenance.

**Closed by jordisala1991** 2018-04-01 21:13 UTC
