### ISSUE TITLE
Create issue when merging a PR containing "NEXT_MAJOR"

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#113] opened 2016-05-29 19:25 UTC
In order to avoid forgetting counterpart PRs, it would be great to have SonataCI create an issue assigned to the author of the PR (not the author of the commits, but the person who created the PR on github), so that he doesn't forget to make the required changes. This could be done at two possible moments : 
1. When the PR is merged.
2. When the stable branch is merged in the unstable branch (this one has my preference).

**Comment by Soullivaneuh** [comment] 2016-05-29 23:19
> issue assigned to the author of the PR (not the author of the commits, but the person who created the PR on github)

Can't be possible, we can only assign Sonata members.

The global idea is very good, but I have no idea of how to handle it. Any suggestion?

**Comment by greg0ire** [comment] 2016-05-30 06:59
> The global idea is very good, but I have no idea of how to handle it. Any suggestion?

No idea either,  I thought you would have one :P Maybe use one of the webhooks ?

**Comment by Soullivaneuh** [comment] 2016-05-30 10:01
Use webhooks or cron, this is not a problem.

The problem is. How we detect NEXT_MAJOR of each PR and what should we put on the issue exactly?

And for the idea, I'm afraid to have lot of automatic issue creation that will still here because the author will create a PR on master and don't notice the related issue...

**Comment by greg0ire** [comment] 2016-05-30 10:03
> And for the idea, I'm afraid to have lot of automatic issue creation that will still here because the author will create a PR on master and don't notice the related issue...

That's why I was proposing assigning the issue, but maybe we can simply ping instead, since it is not possible.

> The problem is. How we detect NEXT_MAJOR of each PR and what should we put on the issue exactly?

You mean there is no way to compare before and after from the information given by the webhook ?

**Comment by Soullivaneuh** [comment] 2016-05-30 10:04
Maybe, I don't know for the moment. :-)

But this don't answer my question about "what should we put on the issue exactly?"

**Comment by greg0ire** [comment] 2016-05-30 10:08
> But this don't answer my question about "what should we put on the issue exactly?"

Right sorry : 

```
Dear contributor, it appears you introduced a `NEXT_MAJOR` tag in PR #{{ pr_number }}.
Would you kindly create a PR against master finishing the job by doing what was recommended and removing the tag?

Best regards,
--
SonataCI
```

**Comment by Soullivaneuh** [comment] 2016-06-02 06:34
So, just create an issue with something like: "Hey you put some `NEXT_MAJOR` tag, please fix them!" Without any precision?

And if the concerned user do several PRs at a time, how should we handle it? One issue by PR? Only one issue for all with different messages (or a todo list)?

BTW, we should precise that the change of the stable branch are maybe not on master yet.

**Comment by greg0ire** [comment] 2016-06-02 08:15
> Without any precision?

Well maybe we could list he introduced occurences of this tag in a todo list?

> And if the concerned user do several PRs at a time, how should we handle it? One issue by PR?

Yes, because he will need to make several PRs for different things anyway, so he might as well close several issues.

> BTW, we should precise that the change of the stable branch are maybe not on master yet.

Or create the issue only when relevant ?

**Comment by Soullivaneuh** [comment] 2016-06-02 08:36
> Or create the issue only when relevant ?

Yeah, but we have to find a way to detect that.

**Comment by greg0ire** [comment] 2016-06-02 08:42
> Yeah, but we have to find a way to detect that.

Run a cron that analyses new merge events done on master, where the name of the merged branch is 3.x ?

**Comment by Soullivaneuh** [comment] 2016-06-02 08:44
Yes, I think I'll start by this way. :-)

**Comment by VincentLanglet** [comment] 2020-08-15 11:23
When I see all the `NEXT_MAJOR` we have on master, I'm scared this could end with lot of new issues created.

Maybe it could be better to just ping people on the PR of 3.x into master when the PR is merged.
"You changes are now merged into master, can you finish the NEXT_MAJOR work ?"

**Comment by VincentLanglet** [comment] 2021-06-06 18:24
If the merge of 3.x into master has conflict, we generally make the merge locally, open a PR, get approval and then push on master. Isn't this restricted to the team ? If contributor are not able to merge 3.x into master, they won't be able to fix most of the `NEXT_MAJOR` comment.

**Closed** 2021-08-15 08:17 UTC
