### ISSUE TITLE
Trigger release announcements on Twitter via dev-kit

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#170] opened 2016-06-15 13:37 UTC
As discussed with @rande and @sonata-project/contributors on Slack.

Find a way to push a new tweet from [Sonata Project account](https://twitter.com/sonataproject) when a new release is written.

Possible way:
1. Tweet directly when it's pushed (Use GitHub event)
2. Tweet at the morning all the new releases (Need database to store already tweeted release)

For `2`, don't tweet a release if another one of the same minor is done after.

**Comment by OskarStark** [comment] 2016-06-15 13:40
I prefer `1` 👍

**Comment by Soullivaneuh** [comment] 2016-06-15 13:43
This is the simple way indeed.

The fact is, if I push a release on the night, the tweet would not be seen by lot of people.

**Comment by OskarStark** [comment] 2016-06-15 13:47
you are right, we could store them in a yaml file or sqlite database and tweet them in the morning around 10

**Comment by Soullivaneuh** [comment] 2016-06-15 13:48
> you are right, we could store them in a yaml file or sqlite database and tweet them in the morning around 10 am

Or 9 am. Except people does not work the morning in Germany? Just kidding. :wink: :stuck_out_tongue: 

We could indeed store "Release to announce" instead of "Already announced releases" to get a lighter database. :+1:

**Comment by OskarStark** [comment] 2016-06-15 13:57
> Or 9 am. Except if people does not work the morning in Germany? Just kidding. 😉 😛

haha 😄

**Comment by greg0ire** [comment] 2016-06-15 13:59
>     Or 9 am. Except if people does not work the morning in Germany? Just kidding. :wink: :stuck_out_tongue:

Well I think you start working pretty early actually, don't you ? As far as I am concerned, I start working at 10, so…

**Comment by Soullivaneuh** [comment] 2016-06-15 14:06
Well, we can consider that work usually start between 9 and 10 AM.

Personally, I'm used to program my tweets at 9AM. So the earlier people start RT, then the other will see it later. :wink:

**Comment by greg0ire** [comment] 2016-06-15 14:07
I was asking @OskarStark , but ok! I think 9 AM is just fine.

**Comment by OskarStark** [comment] 2016-06-15 14:44
We start between 8 and 10 at work

**Comment by VincentLanglet** [comment] 2021-02-17 15:42
I think this could be great for the sonata visibility @sonata-project/contributors 
Does anyone know how to do it ?

**Comment by OskarStark** [comment] 2021-02-17 15:47
We do this already: https://twitter.com/sonatanews

**Comment by VincentLanglet** [comment] 2021-02-17 15:53
Closing then

**Comment by core23** [comment] 2021-02-17 16:16
> We do this already: https://twitter.com/sonatanews

The bot uses IFTTT as a build trigger and contains many manually created rules for each repo.

The issue is still valid for me. We should trigger the tweet via dev-kit.

**Comment by OskarStark** [comment] 2021-02-18 10:56
Oh ok didn't know it needs manual adjustments

**Comment by VincentLanglet** [comment] 2024-04-13 20:30
Looking at the low activity of sonata project, the issue does not seems worth it

**Closed by VincentLanglet** 2024-04-13 20:30 UTC
