### ISSUE TITLE
Remove dummy translation keys

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#751] opened 2020-06-13 07:03 UTC
In the past we had done some mistake with our translation files. We've added the translation key itself as a translation value if we don't know the correct value. This looks wrong. This will also cause problems if you want to rely on the fallback value.

Give the case, that we create a new feature and add some new key. The key will have no meaningful value for know. When a user update their project, they will see some technical text keys instead of some text they can understand (e.g. English fallback keys).

What I want to propose is to remove the dummy (value = key) translations keys. The only problem is that we don't see the missing keys. But maybe we can find a way to automate this via. a GitHub action? I dream of an action that automatically crates an issue for us and lists all missing keys.

So should we remove the default values 👍 or not 👎 ?

Refs: https://github.com/sonata-project/SonataAdminBundle/pull/6134#discussion_r438290375

**Comment by VincentLanglet** [comment] 2020-06-13 07:10
I was trying to add the missing translations https://github.com/sonata-project/SonataAdminBundle/pull/6138 in order to solve this issue.

**Comment by core23** [comment] 2020-06-13 07:48
This will not solve the issue, because nobody speaks all the languages we use (~30 for the admin bundle https://github.com/sonata-project/SonataAdminBundle/tree/3.x/src/Resources/translations). Using Google Translator for all translations will cause other issues.

**Comment by VincentLanglet** [comment] 2020-06-13 08:20
We're lacking of translation contribution.

For example, it's been 7 years, since the `Administration` word was not translated in Deutsch.
https://github.com/sonata-project/SonataAdminBundle/blame/3.x/src/Resources/translations/SonataAdminBundle.de.xliff#L5

Most of our translation require to translate one word or two. Some basics expressions. "Read", "Show", "Admin", ... Using a dictionary, a translator, and checking by doing a reverse translation is most of the time enough for our translations.
And this will be far more better than the actual situation "English words or dummy translation".

By trying to translate the missing keys, I found out that
- It's really hard to find missing key if they were not added to the translations files.
- It's really hard to find missing translations if we used the english translations as default value (like we did for the "DE" Administration key.
So I prefer adding missing keys with dummy translations.

But we're not a project like symfony, with tons of contributors and translators. So I think we should accept to do translations by ourself ; it still better than nothing. And if we made a mistake, one day, maybe, someone gonna make a PR. But when I looked at the git history, it's not happening ofter recently.

**Comment by core23** [comment] 2020-06-14 13:56
> Most of our translation require to translate one word or two. Some basics expressions. "Read", "Show", "Admin", ... Using a dictionary, a translator, and checking by doing a reverse translation is most of the time enough for our translations.

That's right for short imperative words, but there are also some error messages which can confuse (or insult) people if you use a wrong translation.

>  And this will be far more better than the actual situation "English words or dummy translation".

English was just an example. There are some countries that have more than one main language (e.g. Spain) and they can understand other languages too. Using a [fallback languages](https://symfony.com/doc/current/translation.html#fallback-translation-locales) is not an exotic way and some people can even live with a fallback text instead of a technical dummy text.

> We're lacking of translation contribution.

> But we're not a project like symfony, with tons of contributors and translators. 

That's right, maybe there is no active user (anymore) for some of the languages 🤔 IMHO we should no spend or time and energy in translating everything to every translation file that had some translated keys. If someone is using it, he should contribute and add the missing keys.

**Comment by VincentLanglet** [comment] 2020-06-14 15:45
> Using a fallback languages is not an exotic way and some people can even live with a fallback text instead of a technical dummy text.

In our context. With no translations contributions, I feel like using the fallback can lead to regression.

For example: 
- `Admin` key is translated in `Admin` in english, it's the same word in french.
- You add the `Admin` key only for english, every other language used the fallback.
- French default to english and translate to `Admin`. Which is the right word.
- Nobody will add the translation for french, since users thinks it's not missing.
- One day, you decide that `Admin` will be translated to `Administrator` in english.
- Too bad, it's now `Administrator` in french too. Regression introduced.

I really prefer the "show what's missing" strategy, rather than "hide it as much as you can".

> IMHO we should no spend or time and energy in translating everything to every translation file that had some translated keys. 

Then you're debating about something you don't want to spend time or energy 😅 

> If someone is using it, he should contribute and add the missing keys.

Dummy translations has the advantage to promote contribution and make it easier.

**Comment by greg0ire** [comment] 2020-06-14 16:09
Note that the so-called "show what's missing" hides what's missing from the Symfony Inspector. There might even be missing translations that are easier to find that way, like translations used in `title` html attributes.

**Comment by VincentLanglet** [comment] 2020-06-14 16:54
> Note that the so-called "show what's missing" hides what's missing from the Symfony Inspector. There might even be missing translations that are easier to find that way, like translations used in `title` html attributes.

Does the inspector report as missing a translation when using the fallback ?

**Comment by greg0ire** [comment] 2020-06-14 17:09
IIRC it does, but don't take my word for it.

**Comment by VincentLanglet** [comment] 2020-08-15 13:11
Currently, there is no dummy translation keys in SonataAdminBundle. Can we close this ?

**Comment by core23** [comment] 2020-08-15 15:26
IMHO, this is not only a problem in the Admin repo. There are/were some dummy keys in the other repos.

**Comment by VincentLanglet** [comment] 2020-08-15 15:57
> IMHO, this is not only a problem in the Admin repo. There are/were some dummy keys in the other repos.

Indeed, I found these bundle with dummy translation key:
- https://github.com/sonata-project/SonataClassificationBundle/tree/3.x/src/Resources/translations
- https://github.com/sonata-project/SonataCommentBundle/tree/3.x/src/Resources/translations
- https://github.com/sonata-project/SonataFormatterBundle/tree/4.x/src/Resources/translations
- https://github.com/sonata-project/SonataMediaBundle/tree/3.x/src/Resources/translations
- https://github.com/sonata-project/SonataNewsBundle/tree/3.x/src/Resources/translations
- https://github.com/sonata-project/SonataPageBundle/tree/3.x/src/Resources/translations
- https://github.com/sonata-project/SonataUserBundle/tree/4.x/src/Resources/translations

**Comment by VincentLanglet** [comment] 2021-08-07 08:31
As discussed here: https://github.com/sonata-project/SonataMediaBundle/pull/2018#discussion_r684604016

Removing the dummy translations keys have some drawback, like the fact it's hard to know which translations are missing.

Best would be to have
- A page on the dev-kit site the status of the translations of every project, like https://symfony-translations.nyholm.tech/
- Having a CI-check about the order of the translations (every files should use the same order than the en file).

**Comment by jordisala1991** [comment] 2021-08-07 10:46
The are tools for that. I will propose one.

**Comment by VincentLanglet** [comment] 2021-08-07 11:31
> The are tools for that. I will propose one.

I was trying to write something on dev-kit in order to make calls to the github api and display the list of our translations, the missing ones, etc. I will wait for your proposal before continue coding then ^^'

**Comment by jordisala1991** [comment] 2021-08-07 12:10
This is one: https://weblate.org/en-gb/

**Comment by jordisala1991** [comment] 2021-08-07 12:14
Another one: https://crowdin.com/

This one is used in Sylius, and the other one in Taiga.

**Comment by jordisala1991** [comment] 2021-08-15 06:54
Using any of this tools requires not to have this wrong placeholders so this can be closed, it will be done when migrating to weblate.

**Closed by jordisala1991** 2021-08-15 06:55 UTC
